/// <summary>Easy access to KeyCode strings required by cInput</summary>
public enum CInputKeys {

	#region Keyboard input values

	#region Numbers

	Alpha0 ,
	Alpha1 ,
	Alpha2 ,
	Alpha3 ,
	Alpha4 ,
	Alpha5 ,
	Alpha6 ,
	Alpha7 ,
	Alpha8 ,
	Alpha9 ,

	#endregion //Numbers

	#region English alphabet

	A ,
	B ,
	C ,
	D ,
	E ,
	F ,
	G ,
	H ,
	I ,
	J ,
	K ,
	L ,
	M ,
	N ,
	O ,
	P ,
	Q ,
	R ,
	S ,
	T ,
	U ,
	V ,
	W ,
	X ,
	Y ,
	Z ,

	#endregion //English alphabet

	#region Function keys

	F1 ,
	F2 ,
	F3 ,
	F4 ,
	F5 ,
	F6 ,
	F7 ,
	F8 ,
	F9 ,
	F10 ,
	F11 ,
	F12 ,
	F13 ,
	F14 ,
	F15 ,

	#endregion //Function keys

	#region Keypad (Numpad) keys

	Keypad0 ,
	Keypad1 ,
	Keypad2 ,
	Keypad3 ,
	Keypad4 ,
	Keypad5 ,
	Keypad6 ,
	Keypad7 ,
	Keypad8 ,
	Keypad9 ,
	/// <summary>Alternative for and equivalent to Keys.KeypadMultiply</summary>
	KeypadAsterisk ,
	KeypadDivide ,
	KeypadEnter ,
	KeypadEquals ,
	KeypadMinus ,
	KeypadMultiply ,
	KeypadPeriod ,
	KeypadPlus ,
	/// <summary>Alternative for and equivalent to Keys.KeypadDivide</summary>
	KeypadSlash ,

	#endregion //Keypad (Numpad) keys

	#region Other keys

	None ,
	AltGr ,
	Ampersand ,
	/// <summary>Alternative for and equivalent to Keys.Quote</summary>
	Apostrophe ,
	/// <summary>Alternative for and equivalent to Keys.DownArrow</summary>
	ArrowDown ,
	/// <summary>Alternative for and equivalent to Keys.LeftArrow</summary>
	ArrowLeft ,
	/// <summary>Alternative for and equivalent to Keys.RightArrow</summary>
	ArrowRight ,
	/// <summary>Alternative for and equivalent to Keys.UpArrow</summary>
	ArrowUp ,
	Asterisk ,
	AtSymbol ,
	BackQuote ,
	Backslash ,
	Backspace ,
	Break ,
	CapsLock ,
	Caret ,
	Clear ,
	Colon ,
	Comma ,
	Delete ,
	Dollar ,
	DoubleQuote ,
	DownArrow ,
	End ,
	/// <summary>Alternative for and equivalent to Keys.Return</summary>
	Enter ,
	EqualSign ,
	Escape ,
	Exclaim ,
	/// <summary>Alternative for and equivalent to Keys.Exclaim</summary>
	ExclamationMark ,
	/// <summary>Alternative for and equivalent to Keys.Slash</summary>
	ForwardSlash ,
	/// <summary>Alternative for and equivalent to Keys.Greater</summary>
	GreaterThan ,
	Greater ,
	Hash ,
	Help ,
	Home ,
	Insert ,
	LeftAlt ,
	LeftApple ,
	LeftArrow ,
	LeftBracket ,
	LeftControl ,
	LeftParen ,
	LeftShift ,
	LeftWindows ,
	Less ,
	/// <summary>Alternative for and equivalent to Keys.Less</summary>
	LessThan ,
	Menu ,
	Minus ,
	/// <summary>Alternative for and equivalent to Keys.Greater</summary>
	MoreThan ,
	/// <summary>Alternative for and equivalent to Keys.Hash</summary>
	NumberSign ,
	Numlock ,
	PageDown ,
	PageUp ,
	Pause ,
	Period ,
	Plus ,
	/// <summary>Alternative for and equivalent to Keys.Hash</summary>
	PoundSign ,
	Print ,
	/// <summary>Alternative for and equivalent to Keys.Question</summary>
	QuestionMark ,
	Question ,
	/// <summary>This is a single quote (apostrophe). For double quotes, use Keys.DoubleQuote.</summary>
	Quote ,
	Return ,
	RightAlt ,
	RightApple ,
	RightArrow ,
	RightBracket ,
	RightControl ,
	RightParen ,
	RightShift ,
	RightWindows ,
	ScrollLock ,
	Semicolon ,
	Slash ,
	Space ,
	SysReq ,
	Tab ,
	Underscore ,
	UpArrow ,

	#endregion //Other keys

	#endregion //Keyboard input values

	#region Mouse input values

	Mouse0 ,
	Mouse1 ,
	Mouse2 ,
	Mouse3 ,
	Mouse4 ,
	Mouse5 ,
	Mouse6 ,
	MouseUp ,
	MouseDown ,
	MouseLeft ,
	MouseRight ,
	MouseWheelUp ,
	MouseWheelDown ,

	#endregion //Mouse input values

	#region Gamepad values

	#region Gamepad buttons

	JoystickButton0 ,
	JoystickButton1 ,
	JoystickButton2 ,
	JoystickButton3 ,
	JoystickButton4 ,
	JoystickButton5 ,
	JoystickButton6 ,
	JoystickButton7 ,
	JoystickButton8 ,
	JoystickButton9 ,
	JoystickButton10 ,
	JoystickButton11 ,
	JoystickButton12 ,
	JoystickButton13 ,
	JoystickButton14 ,
	JoystickButton15 ,
	JoystickButton16 ,
	JoystickButton17 ,
	JoystickButton18 ,
	JoystickButton19 ,
	Joystick1Button0 ,
	Joystick1Button1 ,
	Joystick1Button2 ,
	Joystick1Button3 ,
	Joystick1Button4 ,
	Joystick1Button5 ,
	Joystick1Button6 ,
	Joystick1Button7 ,
	Joystick1Button8 ,
	Joystick1Button9 ,
	Joystick1Button10 ,
	Joystick1Button11 ,
	Joystick1Button12 ,
	Joystick1Button13 ,
	Joystick1Button14 ,
	Joystick1Button15 ,
	Joystick1Button16 ,
	Joystick1Button17 ,
	Joystick1Button18 ,
	Joystick1Button19 ,
	Joystick2Button0 ,
	Joystick2Button1 ,
	Joystick2Button2 ,
	Joystick2Button3 ,
	Joystick2Button4 ,
	Joystick2Button5 ,
	Joystick2Button6 ,
	Joystick2Button7 ,
	Joystick2Button8 ,
	Joystick2Button9 ,
	Joystick2Button10 ,
	Joystick2Button11 ,
	Joystick2Button12 ,
	Joystick2Button13 ,
	Joystick2Button14 ,
	Joystick2Button15 ,
	Joystick2Button16 ,
	Joystick2Button17 ,
	Joystick2Button18 ,
	Joystick2Button19 ,
	Joystick3Button0 ,
	Joystick3Button1 ,
	Joystick3Button2 ,
	Joystick3Button3 ,
	Joystick3Button4 ,
	Joystick3Button5 ,
	Joystick3Button6 ,
	Joystick3Button7 ,
	Joystick3Button8 ,
	Joystick3Button9 ,
	Joystick3Button10 ,
	Joystick3Button11 ,
	Joystick3Button12 ,
	Joystick3Button13 ,
	Joystick3Button14 ,
	Joystick3Button15 ,
	Joystick3Button16 ,
	Joystick3Button17 ,
	Joystick3Button18 ,
	Joystick3Button19 ,
	Joystick4Button0 ,
	Joystick4Button1 ,
	Joystick4Button2 ,
	Joystick4Button3 ,
	Joystick4Button4 ,
	Joystick4Button5 ,
	Joystick4Button6 ,
	Joystick4Button7 ,
	Joystick4Button8 ,
	Joystick4Button9 ,
	Joystick4Button10 ,
	Joystick4Button11 ,
	Joystick4Button12 ,
	Joystick4Button13 ,
	Joystick4Button14 ,
	Joystick4Button15 ,
	Joystick4Button16 ,
	Joystick4Button17 ,
	Joystick4Button18 ,
	Joystick4Button19 ,

	#endregion //Gamepad buttons

	#region Gamepad axes

	#region Xbox triggers

	/// <summary>This is the same as Joy1Axis9Positive</summary>
	Xbox1TriggerLeft ,
	/// <summary>This is the same as Joy1Axis10Positive</summary>
	Xbox1TriggerRight ,
	/// <summary>This is the same as Joy2Axis9Positive</summary>
	Xbox2TriggerLeft ,
	/// <summary>This is the same as Joy2Axis10Positive</summary>
	Xbox2TriggerRight ,
	/// <summary>This is the same as Joy3Axis9Positive</summary>
	Xbox3TriggerLeft ,
	/// <summary>This is the same as Joy3Axis10Positive</summary>
	Xbox3TriggerRight ,
	/// <summary>This is the same as Joy4Axis9Positive</summary>
	Xbox4TriggerLeft ,
	/// <summary>This is the same as Joy4Axis10Positive</summary>
	Xbox4TriggerRight ,

	#endregion //Xbox triggers

	Joy1Axis1Negative ,
	Joy1Axis1Positive ,
	Joy1Axis2Negative ,
	Joy1Axis2Positive ,
	Joy1Axis3Negative ,
	Joy1Axis3Positive ,
	Joy1Axis4Negative ,
	Joy1Axis4Positive ,
	Joy1Axis5Negative ,
	Joy1Axis5Positive ,
	Joy1Axis6Negative ,
	Joy1Axis6Positive ,
	Joy1Axis7Negative ,
	Joy1Axis7Positive ,
	Joy1Axis8Negative ,
	Joy1Axis8Positive ,
	Joy1Axis9Negative ,
	Joy1Axis9Positive ,
	Joy1Axis10Negative ,
	Joy1Axis10Positive ,
	Joy2Axis1Negative ,
	Joy2Axis1Positive ,
	Joy2Axis2Negative ,
	Joy2Axis2Positive ,
	Joy2Axis3Negative ,
	Joy2Axis3Positive ,
	Joy2Axis4Negative ,
	Joy2Axis4Positive ,
	Joy2Axis5Negative ,
	Joy2Axis5Positive ,
	Joy2Axis6Negative ,
	Joy2Axis6Positive ,
	Joy2Axis7Negative ,
	Joy2Axis7Positive ,
	Joy2Axis8Negative ,
	Joy2Axis8Positive ,
	Joy2Axis9Negative ,
	Joy2Axis9Positive ,
	Joy2Axis10Negative ,
	Joy2Axis10Positive ,
	Joy3Axis1Negative ,
	Joy3Axis1Positive ,
	Joy3Axis2Negative ,
	Joy3Axis2Positive ,
	Joy3Axis3Negative ,
	Joy3Axis3Positive ,
	Joy3Axis4Negative ,
	Joy3Axis4Positive ,
	Joy3Axis5Negative ,
	Joy3Axis5Positive ,
	Joy3Axis6Negative ,
	Joy3Axis6Positive ,
	Joy3Axis7Negative ,
	Joy3Axis7Positive ,
	Joy3Axis8Negative ,
	Joy3Axis8Positive ,
	Joy3Axis9Negative ,
	Joy3Axis9Positive ,
	Joy3Axis10Negative ,
	Joy3Axis10Positive ,
	Joy4Axis1Negative ,
	Joy4Axis1Positive ,
	Joy4Axis2Negative ,
	Joy4Axis2Positive ,
	Joy4Axis3Negative ,
	Joy4Axis3Positive ,
	Joy4Axis4Negative ,
	Joy4Axis4Positive ,
	Joy4Axis5Negative ,
	Joy4Axis5Positive ,
	Joy4Axis6Negative ,
	Joy4Axis6Positive ,
	Joy4Axis7Negative ,
	Joy4Axis7Positive ,
	Joy4Axis8Negative ,
	Joy4Axis8Positive ,
	Joy4Axis9Negative ,
	Joy4Axis9Positive ,
	Joy4Axis10Negative ,
	Joy4Axis10Positive ,

	#endregion //Gamepad axes

	#endregion //Gamepad values

}
